services:

  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_pass
      MYSQL_USER: /run/secrets/db_user_name
      MYSQL_PASSWORD: /run/secrets/db_user_pass
      MYSQL_DATABASE: /run/secrets/db_name
    expose:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
    secrets:
      - db_root_pass
      - db_user_name
      - db_user_pass
      - db_name
  
  osticket:
    image: campbellsoftwaresolutions/osticket:latest
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_pass
      MYSQL_USER: /run/secrets/db_user_name
      MYSQL_PASSWORD: /run/secrets/db_user_pass
      MYSQL_DATABASE: /run/secrets/db_name
    expose:
      - 80
    secrets:
      - db_root_pass
      - db_user_name
      - db_user_pass
      - db_name

  nginx:
    image: nginx:1.27
    depends_on:
      - osticket
    ports:
      - 8080:8080
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/nginx-selfsigned.crt:/etc/certs/nginx-selfsigned.crt
      - ./nginx/certs/nginx-selfsigned.key:/etc/certs/nginx-selfsigned.key

secrets:
  db_root_pass:
    file: ./secrets/db_root_pass.txt
  db_user_name:
    file: ./secrets/db_user_name.txt
  db_user_pass:
    file: ./secrets/db_user_pass.txt
  db_name:
    file: ./secrets/db_name.txt